language: php
php:
  - 7.0
  - 7.1
dist: trusty
sudo: required

env:
  matrix:
    - PHP_COVERAGE_ON=
    - PHP_COVERAGE_ON=y

matrix:
  allow_failures:
    - php: 7.0
      env: PHP_COVERAGE_ON=y
    - php: 7.1
      env: PHP_COVERAGE_ON=y

cache:
  directories:
    - src/node_modules
    - src/vendor

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add travis.php.ini

before_script:
  - cd src/
  - find app resources tests -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - >
    if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then
      bash ../bin/travis-node-setup.sh
    fi
  - travis_retry composer install --no-interaction


script:
  - mkdir -p build/logs
  - >
    if [[ $PHP_COVERAGE_ON = "y" ]]; then
      export PHP_COVERAGE_OPTS="--coverage-clover build/logs/clover.xml";
    fi
  - >
    if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then
      $HOME/node/bin/npm test -- --coverage &&
      phpdbg -qrr vendor/bin/phpunit $PHP_COVERAGE_OPTS -d memory_limit="1G";
    else
      php -d max_execution_time="1800" -d memory_limit="1G" vendor/bin/phpunit;
    fi

after_script:
  - ls -l build/logs/
  - >
    if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then
      if [[ $PHP_COVERAGE_ON = "y" ]]; then
        travis_retry php vendor/bin/coveralls -v;
      else
        $HOME/node/bin/npm install coveralls &&
        cat ./resources/assets/js/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js;
      fi
    fi
